apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: sample
        image: koirand/devops-practice:latest
        ports:
        - containerPort: 8080